### ISSUE TITLE
Rust musl build suddenly crashes on linking binaries

### ISSUE THREAD

**Issue by SamTV12345** [rust-cross/rust-musl-cross#107]
The following error appears when I start the compilation:

[error linking with `armv7-unknown-l.txt](https://github.com/rust-cross/rust-musl-cross/files/11714818/error.linking.with.armv7-unknown-l.txt)

The project builds without a problem in a native environment. Only the docker images suddenly don't work.

**Comment by messense** [comment]
https://www.baeldung.com/linux/error-too-many-open-files

**Comment by SamTV12345** [comment]
Thanks that worked even though I had to run sudo launchctl limit maxfiles 1000000 1000000
