### ISSUE TITLE
Upgrade rustc to Version 1.71.0

### ISSUE THREAD

**Issue by gngpp** [rust-cross/rust-musl-cross#115]
有计划升级一下rust版本吗？容器内手动升级失败了。
![image](https://github.com/rust-cross/rust-musl-cross/assets/51810656/5daf0c63-1a99-4532-a91c-1d097f046607)

项目的一些依赖开始要求比较新版本了，没办法只能本地构建
![image](https://github.com/rust-cross/rust-musl-cross/assets/51810656/9bc3c96e-37a2-44e8-8984-5338f9625459)

**Comment by messense** [comment]
看看是不是缓存的问题，x86_64 musl 上次构建的版本已经是 1.71.0 了：https://github.com/rust-cross/rust-musl-cross/actions/runs/5566557278/job/15075080083#step:8:1714
