### ISSUE TITLE
/usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found

### ISSUE THREAD

**Issue by addame2** [rust-cross/rust-musl-cross#167]
#15 252.8   cargo:root=/usr/src/qvisa/target/aarch64-unknown-linux-musl/release/build/rboring-sys-c1748c2b9b2e4403/out
#15 252.8   running: cd "/usr/src/qvisa/target/aarch64-unknown-linux-musl/release/build/rboring-sys-c1748c2b9b2e4403/out/build" && CMAKE_PREFIX_PATH="" "cmake" "/usr/src/qvisa/target/aarch64-unknown-linux-musl/release/build/rboring-sys-c1748c2b9b2e4403/out/boringssl" "-DCMAKE_CROSSCOMPILING=true" "-DCMAKE_C_COMPILER_TARGET=aarch64-unknown-linux-musl" "-DCMAKE_CXX_COMPILER_TARGET=aarch64-unknown-linux-musl" "-DCMAKE_ASM_COMPILER_TARGET=aarch64-unknown-linux-musl" "-DCMAKE_TOOLCHAIN_FILE=/root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rboring-sys-4.11.1/cmake/aarch64-linux.cmake" "-DCMAKE_INSTALL_PREFIX=/usr/src/qvisa/target/aarch64-unknown-linux-musl/release/build/rboring-sys-c1748c2b9b2e4403/out" "-DCMAKE_C_FLAGS= -ffunction-sections -fdata-sections -fPIC" "-DCMAKE_CXX_FLAGS= -ffunction-sections -fdata-sections -fPIC" "-DCMAKE_ASM_FLAGS= -ffunction-sections -fdata-sections -fPIC" "-DCMAKE_BUILD_TYPE=MinSizeRel"
#15 252.8   -- Configuring done
#15 252.8   -- Generating done
#15 252.8   -- Build files have been written to: /usr/src/qvisa/target/aarch64-unknown-linux-musl/release/build/rboring-sys-c1748c2b9b2e4403/out/build
#15 252.8   running: cd "/usr/src/qvisa/target/aarch64-unknown-linux-musl/release/build/rboring-sys-c1748c2b9b2e4403/out/build" && MAKEFLAGS="-j --jobserver-fds=10,13 --jobserver-auth=10,13" "cmake" "--build" "." "--target" "crypto" "--config" "MinSizeRel"
#15 252.8   Scanning dependencies of target crypto
#15 252.8   Consolidate compiler generated dependencies of target crypto
#15 252.8   [100%] Built target crypto
#15 252.8   cargo:root=/usr/src/qvisa/target/aarch64-unknown-linux-musl/release/build/rboring-sys-c1748c2b9b2e4403/out
#15 252.8   cargo:rustc-link-search=native=/usr/src/qvisa/target/aarch64-unknown-linux-musl/release/build/rboring-sys-c1748c2b9b2e4403/out/build/crypto/
#15 252.8   cargo:rustc-link-search=native=/usr/src/qvisa/target/aarch64-unknown-linux-musl/release/build/rboring-sys-c1748c2b9b2e4403/out/build/ssl/
#15 252.8   cargo:rustc-link-search=native=/usr/src/qvisa/target/aarch64-unknown-linux-musl/release/build/rboring-sys-c1748c2b9b2e4403/out/build/
#15 252.8   cargo:rustc-link-lib=static=crypto
#15 252.8   cargo:rustc-link-lib=static=ssl
#15 252.8 
#15 252.8   --- stderr
#15 252.8   hint: Using 'master' as the name for the initial branch. This default branch name
#15 252.8   hint: is subject to change. To configure the initial branch name to use in all
#15 252.8   hint: of your new repositories, which will suppress this warning, call:
#15 252.8   hint: 
#15 252.8   hint: 	git config --global init.defaultBranch <name>
#15 252.8   hint: 
#15 252.8   hint: Names commonly chosen instead of 'master' are 'main', 'trunk' and
#15 252.8   hint: 'development'. The just-created branch can be renamed via this command:
#15 252.8   hint: 
#15 252.8   hint: 	git branch -m <name>
#15 252.8 
#15 252.8   /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rboring-sys-4.11.1/patches/boringssl-old-ciphers.patch:25: trailing whitespace.
#15 252.8    
#15 252.8   /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rboring-sys-4.11.1/patches/boringssl-old-ciphers.patch:27: trailing whitespace.
#15 252.8    
#15 252.8   /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rboring-sys-4.11.1/patches/boringssl-old-ciphers.patch:58: trailing whitespace.
#15 252.8    
#15 252.8   /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rboring-sys-4.11.1/patches/boringssl-old-ciphers.patch:214: trailing whitespace.
#15 252.8   // 
#15 252.8   /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rboring-sys-4.11.1/patches/boringssl-old-ciphers.patch:219: trailing whitespace.
#15 252.8   // 
#15 252.8   Checking patch src/ssl/internal.h...
#15 252.8   Hunk #1 succeeded at 556 (offset -21 lines).
#15 252.8   Checking patch src/ssl/ssl_cipher.cc...
#15 252.8   Hunk #6 succeeded at 657 (offset -4 lines).
#15 252.8   Hunk #7 succeeded at 1279 (offset -2 lines).
#15 252.8   Checking patch src/ssl/ssl_privkey.cc...
#15 252.8   Hunk #1 succeeded at 569 (offset 9 lines).
#15 252.8   Applied patch src/ssl/internal.h cleanly.
#15 252.8   Applied patch src/ssl/ssl_cipher.cc cleanly.
#15 252.8   Applied patch src/ssl/ssl_privkey.cc cleanly.
#15 252.8   warning: squelched 2 whitespace errors
#15 252.8   warning: 7 lines applied after fixing whitespace errors.
#15 252.8 
#15 252.8   /usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found
#15 252.8   thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rboring-sys-4.11.1/build/main.rs:762:39:
#15 252.8   Unable to generate bindings: ClangDiagnostic("/usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found\n")
#15 252.8   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
#15 252.8 warning: build failed, waiting for other jobs to finish...
#15 ERROR: process "/bin/sh -c cargo build --release --target aarch64-unknown-linux-musl" did not complete successfully: exit code: 101
------
 > [builder 5/5] RUN cargo build --release --target aarch64-unknown-linux-musl:
252.8   Applied patch src/ssl/ssl_cipher.cc cleanly.
252.8   Applied patch src/ssl/ssl_privkey.cc cleanly.
252.8   warning: squelched 2 whitespace errors
252.8   warning: 7 lines applied after fixing whitespace errors.
252.8 
252.8   /usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found
252.8   thread 'main' panicked at /root/.cargo/registry/src/index.crates.io-6f17d22bba15001f/rboring-sys-4.11.1/build/main.rs:762:39:
252.8   Unable to generate bindings: ClangDiagnostic("/usr/include/stdint.h:26:10: fatal error: 'bits/libc-header-start.h' file not found\n")
252.8   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
252.8 warning: build failed, waiting for other jobs to finish...
------

 1 warning found (use docker --debug to expand):
 - FromAsCasing: 'as' and 'FROM' keywords' casing do not match (line 2)
Dockerfile:18
--------------------
  16 |     
  17 |     # Build the project using Cargo in release mode
  18 | >>> RUN cargo build --release --target aarch64-unknown-linux-musl
  19 |     
  20 |     # Use a minimal base image for running the built binary
--------------------
ERROR: failed to solve: process "/bin/sh -c cargo build --release --target aarch64-unknown-linux-musl" did not complete successfully: exit code: 101
Error: Process completed with exit code 1.

error: linking with `aarch64-unknown-linux-musl-gcc` failed: exit status: 1

2 days trying no success :( 

issue only when I try to build image for ARM64
https://gist.github.com/saroar/826aa3ab944237fd1ba90c1e6f69ac68

no problem https://gist.github.com/saroar/77bba0a6e0536463faa9322c766aa046 for x86_64

**Comment by addame2** [comment]
new errors and docker file 
https://gist.github.com/saroar/d4efd29bf510a51053647889ef9d5f60

**Comment by messense** [comment]
You need to tell bindgen where to find sysroot when cross compiling, see https://github.com/rust-lang/rust-bindgen?tab=readme-ov-file#environment-variables
